/**
 * Validated News Sources Configuration
 * Updated based on RSS feed validation results
 * Last validated: 2025-07-10
 */

import { NewsSource } from '@/types/news';

export const VALIDATED_NEWS_SOURCES: NewsSource[] = [
  // BBC News - All redirected to HTTPS
  {
    id: 'bbc-world',
    name: 'BBC World News',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  {
    id: 'bbc-business',
    name: 'BBC Business News',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    category: 'business',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  {
    id: 'bbc-technology',
    name: 'BBC Technology News',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  {
    id: 'bbc-sport',
    name: 'BBC Sport',
    type: 'rss',
    url: 'https://feeds.bbci.co.uk/sport/rss.xml',
    category: 'sports',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },

  // CNN - Still using HTTP, but working
  {
    id: 'cnn-world',
    name: 'CNN World News',
    type: 'rss',
    url: 'http://rss.cnn.com/rss/edition_world.rss',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  // Note: CNN Business feed is outdated (last update 2018)
  {
    id: 'cnn-top',
    name: 'CNN Top Stories',
    type: 'rss',
    url: 'http://rss.cnn.com/rss/cnn_topstories.rss',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },

  // The Guardian
  {
    id: 'guardian-world',
    name: 'The Guardian World News',
    type: 'rss',
    url: 'https://www.theguardian.com/world/rss',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },

  // Technology
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    type: 'rss',
    url: 'https://techcrunch.com/feed/',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'verge',
    name: 'The Verge',
    type: 'rss',
    url: 'https://www.theverge.com/rss/index.xml',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'ars-technica',
    name: 'Ars Technica',
    type: 'rss',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'wired',
    name: 'Wired',
    type: 'rss',
    url: 'https://www.wired.com/feed/rss',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Technology Review',
    type: 'rss',
    url: 'https://www.technologyreview.com/feed/',
    category: 'technology',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },

  // Business
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    type: 'rss',
    url: 'https://feeds.bloomberg.com/markets/news.rss',
    category: 'business',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  {
    id: 'ft',
    name: 'Financial Times',
    type: 'rss',
    url: 'https://www.ft.com/rss/home/uk',
    category: 'business',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'forbes',
    name: 'Forbes',
    type: 'rss',
    url: 'https://www.forbes.com/real-time/feed2/',
    category: 'business',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },

  // Science
  {
    id: 'nature-news',
    name: 'Nature News',
    type: 'rss',
    url: 'https://www.nature.com/nature.rss',
    category: 'science',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'science-daily',
    name: 'Science Daily',
    type: 'rss',
    url: 'https://www.sciencedaily.com/rss/all.xml',
    category: 'science',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'new-scientist',
    name: 'New Scientist',
    type: 'rss',
    url: 'https://www.newscientist.com/feed/home',
    category: 'science',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'nasa',
    name: 'NASA News',
    type: 'rss',
    url: 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
    category: 'science',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },

  // Sports
  {
    id: 'espn',
    name: 'ESPN',
    type: 'rss',
    url: 'https://www.espn.com/espn/rss/news',
    category: 'sports',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'sky-sports',
    name: 'Sky Sports',
    type: 'rss',
    url: 'https://www.skysports.com/rss/12040',
    category: 'sports',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },

  // Entertainment
  {
    id: 'variety',
    name: 'Variety',
    type: 'rss',
    url: 'https://variety.com/feed/',
    category: 'entertainment',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'hollywood-reporter',
    name: 'The Hollywood Reporter',
    type: 'rss',
    url: 'https://www.hollywoodreporter.com/feed',
    category: 'entertainment',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'rolling-stone',
    name: 'Rolling Stone',
    type: 'rss',
    url: 'https://www.rollingstone.com/feed/',
    category: 'entertainment',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'deadline',
    name: 'Deadline',
    type: 'rss',
    url: 'https://deadline.com/feed/',
    category: 'entertainment',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },

  // Politics
  {
    id: 'the-hill',
    name: 'The Hill',
    type: 'rss',
    url: 'https://thehill.com/feed/?feed=partnerfeed-news-feed&format=rss',
    category: 'politics',
    language: 'en',
    enabled: true,
    updateInterval: 60,
  },
  {
    id: 'foreign-policy',
    name: 'Foreign Policy',
    type: 'rss',
    url: 'https://foreignpolicy.com/feed/',
    category: 'politics',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
  {
    id: 'economist',
    name: 'The Economist',
    type: 'rss',
    url: 'https://www.economist.com/international/rss.xml',
    category: 'politics',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },

  // General/Mixed
  {
    id: 'npr',
    name: 'NPR News',
    type: 'rss',
    url: 'https://feeds.npr.org/1001/rss.xml',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },
  {
    id: 'al-jazeera',
    name: 'Al Jazeera English',
    type: 'rss',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    category: 'world',
    language: 'en',
    enabled: true,
    updateInterval: 30,
  },

  // Health - Working feeds only
  {
    id: 'who-news',
    name: 'WHO News',
    type: 'rss',
    url: 'https://www.who.int/rss-feeds/news-english.xml',
    category: 'health',
    language: 'en',
    enabled: true,
    updateInterval: 120,
  },
];

// Feeds that were found to be broken or unavailable:
export const BROKEN_FEEDS = [
  'Reuters (all feeds) - Domain not found',
  'Harvard Business Review - TLS connection error',
  'Scientific American - TLS connection error',
  'WebMD - Server error 500',
  'Mayo Clinic - Forbidden 403',
  'Medical News Today - Forbidden 403',
  'Harvard Health - Not found 404',
  'The Athletic - Redirects to NYTimes, 404',
  'Sports Illustrated - Not found 404',
  'Entertainment Weekly - Domain not found',
  'Politico - Forbidden 403',
];

// Export for backward compatibility
export const NEWS_SOURCES = VALIDATED_NEWS_SOURCES;